name: Check Markdown links

on: 
  [push, pull_request]
 
jobs:
  markdown-link-check:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/MarkdownLinksCheck.yml@main
    with:
      folder-path: 'Evaluation/report'
